"""Configuration package for Article Person Verification."""

from .settings import (
    GOOGLE_API_KEY,
    GEMINI_MODEL_NAME,
    MLFLOW_TRACKING_URI,
    MLFLOW_EXPERIMENT_NAME,
    REQUEST_HEADERS,
    REQUEST_TIMEOUT,
    DEFAULT_TEST_CASES_FILE
)

from .prompts import (
    NAME_PRESENCE_PROMPT,
    AGE_VERIFICATION_PROMPT,
    DETAIL_VERIFICATION_PROMPT,
    SENTIMENT_ANALYSIS_PROMPT
)

__all__ = [
    'GOOGLE_API_KEY',
    'GEMINI_MODEL_NAME',
    'MLFLOW_TRACKING_URI',
    'MLFLOW_EXPERIMENT_NAME',
    'REQUEST_HEADERS',
    'REQUEST_TIMEOUT',
    'DEFAULT_TEST_CASES_FILE',
    'NAME_PRESENCE_PROMPT',
    'AGE_VERIFICATION_PROMPT',
    'DETAIL_VERIFICATION_PROMPT',
    'SENTIMENT_ANALYSIS_PROMPT'
]
